INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (1, 'Zilda','Gomes', 30, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (2, 'Marta', 'Gomes', 14, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (3, 'Bruna', 'Ribeiro', 33, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (4, 'Bruno', 'da Silva', 23, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (5, 'Carlos Andre', 'Rios', 30, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (6, 'Maria Aparecida', 'Silva', 15, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (7, 'Luciana', 'Martins', 40, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (8, 'Rodrigo', 'Dutra', 20, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (9, 'Ricardo', 'Oliveira', 14, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (10, 'Vagner', 'da Rosa', 16, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (11, 'José', 'dos Santos', 13, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (12, 'Pedro', 'Martins', 14, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (13, 'Pietra', 'Fernandes', 27, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (14, 'Marilia', 'Onis', 17, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (15, 'Fabiano', 'Vidal', 14, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (16, 'Lucas', 'de Souza', 15, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (17, 'Bruna', 'Romero', 25, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (18, 'Magnun Luiz', 'da Silva', 52, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (19, 'Ricardo José', 'Silveira', 35, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (20, 'Mirian', 'Rodrigues', 12, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (21, 'Vinicius Otávio', 'Souza', 13, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (22, 'Cristiano', 'Ferreira', 23, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (23, 'Carlos', 'Marin', 18, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (24, 'Olivia', 'da Silva', 34, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (25, 'Cintia', 'Colombo', 38, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (26, 'Anete', 'Caceres', 26, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (27, 'Aline Maria', 'Ribeiro', 19, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (28, 'Mario Nelson', 'Diogenes', 24, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (29, 'Bruna', 'Ribas', 34, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (30, 'Juliana', 'Pinto', 22, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (31, 'Liliana', 'Pires', 16, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (32, 'Marcio', 'Olavo', 17, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (33, 'Anelise', 'Ferreira', 26, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (34, 'Anita', 'Rulins', 29, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (35, 'Mario', 'Hargo', 36, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (36, 'Pedro', 'Junqueira', 20, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (37, 'Emerson', 'Belina', 31, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (38, 'Gustavo', 'H. Lopes', 36, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (39, 'Giuliano', 'J. Fagundes', 43, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (40, 'Victor', 'Ferreira', 50, 'M');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (41, 'Olivia', 'Ribeiro', 25, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (42, 'Julia', 'Soares', 23, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (43, 'Isabel', 'Ferreira', 11, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (44, 'Olivia', 'Melo', 34, 'F');
INSERT INTO CONTATOS (id, nome, sobrenome, idade, sexo) VALUES (45, 'Murilio', 'Ferreira', 34, 'M');